default: &default
 adapter: postgresql
 encoding: unicode
 pool: 5
 username: blog
 host: localhost
 password: 'password1'

development:
 <<: *default
 database: blog_development

test:
 <<: *default
 database: blog_test

